### PR TITLE
Catch OutOfMemoryError and set imageView GONE

### PR DESCRIPTION
**Pull request by joeykrim**
On a few devices, I've received an OutOfMemoryError exception crashing the app when setting the ImageResource.
Porposing to catch the out of memory exception and hiding the image rather than crashing the device.

### CODE REVIEW

**Comment by joeykrim** [comment]
travis ci build failed due to a configuration issue on the build instance: the license hasn't been accepted for ConstraintLayout v1.0.2

File /home/travis/.android/repositories.cfg could not be loaded.
Checking the license for package Solver for ConstraintLayout 1.0.2 in /usr/local/android-sdk/licenses
Warning: License for package Solver for ConstraintLayout 1.0.2 not accepted.
Checking the license for package ConstraintLayout for Android 1.0.2 in /usr/local/android-sdk/licenses
Warning: License for package ConstraintLayout for Android 1.0.2 not accepted.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':library'.
      > You have not accepted the license agreements of the following SDK components:
        [ConstraintLayout for Android 1.0.2, Solver for ConstraintLayout 1.0.2].
        Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
        Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 33.656 secs
The command "./gradlew build connectedCheck" exited with 1.
Done. Your build exited with 1.

**Comment by heinrichreimer** [comment]
@MFlisar Could you please merge https://github.com/joeykrim/material-intro/pull/1 to fix issues with the Travis CI build?

**Comment by chimbori** [comment]
Hello, new maintainer here! Thanks for your PR; I realize that some time has passed since this PR was last proposed, so I certainly understand if you are no longer able to devote time to this, but if you are able to, I would love to see the comments addressed. Of course, I fully understand if you are not able to — could you please let me know either way? I am hoping to close any pending open PRs before cutting a new release. Thanks!

**Comment by joeykrim** [comment]
> @joeykrim Could you please merge [joeykrim#1](https://github.com/joeykrim/material-intro/pull/1) to fix issues with the Travis CI build?



> Hello, new maintainer here! Thanks for your PR; I realize that some time has passed since this PR was last proposed, so I certainly understand if you are no longer able to devote time to this, but if you are able to, I would love to see the comments addressed. Of course, I fully understand if you are not able to — could you please let me know either way? I am hoping to close any pending open PRs before cutting a new release. Thanks!

Done - let me know if there's anything else to be done to merge

**Pull request merged**
