### PR TITLE
Add prefix to avoid collision with app using lib

### PR DESCRIPTION
**Pull request by odin-**
I did not fix Theme name in themes.xml. Perhaps that should be renamed also...

### CODE REVIEW

**Comment by odin-** [comment]
I renamed all resources. If that's too much just tell me and I'll just rename frags and layout.

**Comment by HeinrichReimer** [comment]
On a side note: do you agree that the code will be published under the MIT license? I'm currently switching out the Apache license for the more permissive MIT license as you can read in #176

**Comment by HeinrichReimer** [comment]
Ah and I don't think adding a prefix to the themes would be necessary as they are already prefixed `Theme.Intro.` and more importantly they are part of the public API so we can't change that without depreciating the old name slowly.

**Comment by odin-** [comment]
Seems to work (attaching picture).
autocompletion

MIT sounds like the saner choice. I am all in :-)

**Comment by HeinrichReimer** [comment]
Oh, I meant in the layout editor when you edit the layout XML. Sorry, I must've made this more clear.

**Comment by odin-** [comment]
OK, I'll check that and amend if needed.

**Comment by odin-** [comment]
I had some problems getting autocomplete to work with both the new and old. So I cannot prove my change works -> revert changes for the attributes.

**Pull request merged**
