### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by Maxr1998**
Test if Views are available (to prevent Exceptions in custom layouts), improve permission update handling, temporarily fix after-rotation lock bug #20 (I hope).

### CODE REVIEW

**Comment by Maxr1998** [comment]
Why didn't you merge this PR?
I wasn't only thought to fix #20, it also improved error handling and permission handling.

**Comment by HeinrichReimer** [comment]
The conditional allocation doesn't improve code readability. And in terms of performance there won't be any measurable difference between this and the if-else-statement.

**Comment by HeinrichReimer** [comment]
The error handling is already part of the latest code.

**Comment by Maxr1998** [comment]
Oh, I didn't see that. Still, you should take a look at the way I handle background luminance specific text color, that part is pretty duplicated. The new error handling is better than mine for code readability, of course.

**Comment by HeinrichReimer** [comment]
I removed redundancy in this commit: f525022cacc4b4ecbd9d98191449d15cf0aac6aa

**Edit:** fixed a bug in that commit by this commit: cb45cd1ddee910906b80aaec2edb945b4966d8cf

**Comment by Maxr1998** [comment]
Thanks! The code now is a lot cleaner :)

**Pull request closed without merging**
