### PR TITLE
Danish translation

### PR DESCRIPTION
**Pull request by Sumsar**

### CODE REVIEW

**Comment by Sumsar** [comment]
It's translated. It's embedded in the strings.xml

**Comment by HeinrichReimer** [comment]
Well that's not good obviously because the library dependency only includes the library and not the sample app.

**Comment by HeinrichReimer** [comment]
Would you mind splitting the two files and creating a new PR?
I had to revert the old one.

**Comment by Sumsar** [comment]
Ahh I see sorry - let me split it up

**Comment by HeinrichReimer** [comment]
@Sumsar No problem! Great to see some international users!

**Pull request merged**
