### PR TITLE
bugfix - mix of int and long

### PR DESCRIPTION
**Pull request by MFlisar**
solves #243

### CODE REVIEW

**Comment by heinrichreimer** [comment]
Seems like Travis Ci is having some license issues, I'll try to get it to work later today.

**Comment by MFlisar** [comment]
I've accepted the license while the check was running, don't know if I can retrigger travis?

**Comment by heinrichreimer** [comment]
@MFlisar it's not because of the CLA but because of some Android support library licenses.
I've had this problem before with Travis CI and I do know how to resolve it. Just need to get home to fix it.

**Comment by MFlisar** [comment]
you're right, did not read exactly enough... There's no need to hurry anyway

**Comment by meierjan** [comment]
I think if #242 is merged he can pull the changes and travis will succeed again.

**Comment by heinrichreimer** [comment]
@meierjan I'm going to restart the Travis build. Let's see if it works out then.

**Comment by meierjan** [comment]
@heinrichreimer this branch needs to get the changes from the master to have a working build. @MFlisar can u do that?

**Comment by heinrichreimer** [comment]
@MFlisar Could you please merge https://github.com/MFlisar/material-intro/pull/1 to fix issues with the Travis CI build?

**Comment by MFlisar** [comment]
@heinrichreimer 
Merged my clone with the current master branch... Have not tested it though...

**Pull request merged**
