### PR TITLE
Added Support for changing parallaxFactor programatically

### PR DESCRIPTION
**Pull request by iampkhan**
While doing one of my projects I wanted to add some child views to the ParallaxLinearLayout dynamically from java source, but to add parallax effect to them programatically these changes are necessary.

### CODE REVIEW

**Comment by HeinrichReimer** [comment]
You should change `pFactor` to `parallaxFactor`

**Comment by iampkhan** [comment]
The class already contains a field with the same name

**Comment by HeinrichReimer** [comment]
Didn't you know the `this` keyword?
Just rename the method parameter and then assign the variable like this:

```java
this.parallaxFactor = parallaxFactor;
```

**Comment by iampkhan** [comment]
I completely forgot about the this keyword, my mistake, updated the code

**Pull request merged**
