### PR TITLE
Updated to API 26

### PR DESCRIPTION
**Pull request by AkshayChordiya**
Updated to API 26 to automatically add support for Lifecycle from Architecture Components.

### CODE REVIEW

**Comment by AkshayChordiya** [comment]
That's awesome. Meanwhile I have local copy of the library updated to API 27 and some more goodies.

**Comment by meierjan** [comment]
Hey, if level 27 is working why not close this one and go with an update to 27?

**Comment by heinrichreimer** [comment]
@MFlisar Could you please merge https://github.com/AkshayChordiya/material-intro/pull/1 to fix issues with the Travis CI build?

**Comment by AkshayChordiya** [comment]
@meierjan Let's merge this and I'll add another pull request to update to API 27

**Comment by heinrichreimer** [comment]
#245 already includes updating to API 27

**Pull request closed without merging**
