### PR TITLE
fix: crash while inflating ImageButton in mi_activity_intro.xml

### PR DESCRIPTION
**Pull request by firefinchdev**

### CODE REVIEW

**Comment by heinrichreimer** [comment]
Can you confirm, that replacing the color reference with the hex value fixes the issue?

**Comment by firefinchdev** [comment]
As of now, I cant confirm the same. But searching this issue on net, I think this is the only solution.
https://stackoverflow.com/a/35449255/8183406
I will use the "change" in my own app update, and can only tell you if the issue reoccurs or not after few days of usage on production.

**Comment by heinrichreimer** [comment]
So you have not been able to reproduce #283?

**Comment by firefinchdev** [comment]
Not released my update yet, Will take some time, and need another few days to test if issue reoccurs.

**Comment by firefinchdev** [comment]
Please note that I was unable to reproduce the issue on my own devices, but firebase crashlytics showed many devices where the issue occurs.

**Comment by heinrichreimer** [comment]
I would like to see a reproduction of #283 first, before merging this PR.

**Comment by firefinchdev** [comment]
Okay, will report back after some days of next release.

**Comment by firefinchdev** [comment]
So I deployed these changes on production, and in 7 days, there was no reoccurrence of the issue. Earlier, I had 10-15 crashes per day, but not even one on the latest release.

**Comment by firefinchdev** [comment]
@heinrichreimer Is it possible now to merge the PR?

**Comment by firefinchdev** [comment]
Also, please take a look at https://github.com/heinrichreimer/material-intro/issues/285, that issue is at the  top (in terms of number of crashes) in my crashlytics console.
I tried resolving this issue, but was unable to resolve it.

**Pull request merged**
